local utils = require("alqaholic.utils")
local import = utils.safe_require

import("alqaholic.core.options")
import("alqaholic.core.keymaps")
import("alqaholic.core.colorscheme")
import("alqaholic.plugin-setup")
import("alqaholic.plugins.comment")
import("alqaholic.plugins.nvim-tree")
import("alqaholic.plugins.lualine")
import("alqaholic.plugins.gitsigns")
import("alqaholic.plugins.treesitter")
import("alqaholic.plugins.telescope")
import("alqaholic.plugins.completion")
import("alqaholic.plugins.lsp")
